import {describe,it,expect} from 'vitest';
import {Computer} from './computer';
function setup(){const textarea=document.createElement('textarea'),run=document.createElement('button');document.body.replaceChildren(textarea,run);return {textarea,run,c:new Computer(textarea,run)};}
describe('virtual computer actual event path',()=>{
 it('expands a token into keydown/input/keyup and runs through the same click handler',async()=>{const {textarea,run,c}=setup();let clicks=0,inputs=0;run.onclick=()=>{clicks++;};textarea.addEventListener('input',()=>inputs++);const events=await c.perform('<h1>Hello</h1>',16,false,()=>false);expect(textarea.value).toBe('\n<h1>Hello</h1>');expect(inputs).toBe(15);expect(clicks).toBe(1);expect(events.filter(e=>e.type==='keydown').map(e=>e.key).join('')).toBe('End\n<h1>Hello</h1>');expect(events.every((e,i)=>e.tick===17+i&&e.decisionTick===16)).toBe(true);expect(events.at(-1)?.type).toBe('run');expect(document.activeElement).toBe(run);c.dispose();});
 it('supports real corrective backspace, cursor, delete and selection edits',()=>{const {textarea,c}=setup();c.key('a');c.key('b');c.key('c');c.key('ArrowLeft');c.key('Backspace');expect(textarea.value).toBe('ac');c.key('Delete');expect(textarea.value).toBe('a');c.key('Enter');c.key('x');expect(textarea.value).toBe('a\nx');textarea.setSelectionRange(0,3);c.key('z');expect(textarea.value).toBe('z');c.dispose();});
 it('does not mutate source when finishing and aborts a stopped action',async()=>{const {textarea,c}=setup();textarea.value='unchanged';expect(await c.perform(null,16,false,()=>false)).toEqual([]);expect(textarea.value).toBe('unchanged');await expect(c.perform('abc',32,false,()=>true)).rejects.toThrow('stopped');expect(textarea.value).toBe('unchanged');c.dispose();});
 it('replays the identical primitive event stream',async()=>{const a=setup();const one=await a.c.perform('hi',16,false,()=>false);a.c.dispose();const b=setup();const two=await b.c.perform('hi',16,false,()=>false);expect(one).toEqual(two);expect(a.textarea.value).toBe(b.textarea.value);b.c.dispose();});
});
